FIELDS = [
    'height',
    'hash',
    'tx-fully-shielded',
    'tx-truly-mixed',
    'tx-shielding',
    'tx-unshielding',
    'tx-transparent',
    'js-count',
    'cumulative-js-count',
    'coinbase',
    'monetary-base',
    'mb-shielded',
    'mb-shielding',
    'mb-unshielding',
]
